# Generated by Django 2.2.12 on 2021-04-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_auto_20210407_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delevent',
            name='description',
            field=models.TextField(),
        ),
    ]
